// Joueurs pro de référence, classés par grande catégorie de poste.
// Une seule liste sert aux deux côtés (latéral droit/gauche, ailier droit/gauche).
const PLAYERS_BY_CATEGORY = {
  gardien: [
    ["Lev Yashin", ["Agilité", "Régularité"]],
    ["Gianluigi Buffon", ["Réflexes", "Leadership", "Professionnalisme"]],
    ["Manuel Neuer", ["Gardien libéro", "Régularité", "Solidité", "Jeu au pied"]],
    ["Iker Casillas", ["Complet", "Exemplaire"]],
    ["Oliver Kahn", ["Détermination", "Leadership", "Redoutable"]],
    ["Peter Cech", ["Constance", "Courage"]],
    ["Peter Schmeichel", ["Imposant", "Grand", "Pilier"]],
    ["Edwin Van Der Sar", ["Calme", "Régularité", "Fiabilité"]],
    ["Alisson Becker", ["Complet", "Professionnalisme"]],
    ["Thibaut Courtois", ["Envergure", "Agilité"]],
    ["Dida", ["Artiste", "Réflexes", "Expert pénalty", "Calme"]],
    ["Hugo Lloris", ["Fiabilité", "Exemplarité", "Réflexes"]],
    ["Fabien Barthez", ["Explosivité", "Calme", "Face à face", "Réflexes"]],
    ["Victor Valdes", ["Jeu au pied", "Réflexes"]],
    ["Keylor Navas", ["Mental", "Réflexes", "Exemplarité"]],
    ["Jan Oblak", ["Constance", "Placement", "Réflexes"]],
    ["Gianluigi Donnarumma", ["Irrégulier", "Exceptionnel sur la ligne", "Réflexes", "Envergure"]],
    ["Emiliano Martinez", ["Provocateur", "Mental", "Lecture du jeu", "Expert pénalty"]],
    ["Marc-André Ter Stegen", ["Jeu au pied", "Reflex", "Lecture du jeu"]],
    ["David De Gea", ["Imposant", "Reflex"]],
  ],

  defenseur: [
    ["Franz Beckenbauer", ["relance", "vision de jeu", "charisme"]],
    ["Franco Baresi", ["intelligence tactique", "leadership", "libéro", "organisateur"]],
    ["Paolo Maldini", ["élégance", "technique", "sens du placement", "régularité"]],
    ["Alessandro Nesta", ["élégance", "placement", "technique", "intelligence tactique", "sérénité"]],
    ["Fabio Cannavaro", ["placement", "anticipation"]],
    ["Virgil Van Dijk", ["puissance", "vitesse", "intelligence de jeu"]],
    ["Nemanja Vidic", ["roc défensif", "engagement total", "puissance physique", "détermination"]],
    ["Sergio Ramos", ["agressivité", "sens du but", "complet"]],
    ["Carles Puyol", ["leadership", "infatigable", "engagement total", "combativité", "exemplaire"]],
    ["Lilian Thuram", ["puissance", "intelligence", "polyvalent"]],
    ["Rio Ferdinand", ["calme", "vision du jeu", "leadership"]],
    ["Gerard Piqué", ["calme", "grand", "intelligence de jeu"]],
    ["Marquinhos", ["lecture du jeu", "polyvalence", "exemplaire", "mentalité"]],
    ["Saliba", ["puissance", "placement", "propre", "sérénité"]],
    ["Dias", ["communication", "sens du placement", "impact", "perfectionnisme"]],
    ["Antonio Rüdiger", ["agressif", "combat", "engagement total"]]
  ],

  lateral: [
    ["Roberto Carlos", ["puissance", "charisme", "offensif"]],
    ["Cafu", ["vitesse", "endurance", "leadership"]],
    ["Philipp Lahm", ["intelligence tactique", "polyvalent", "propre", "efficace"]],
    ["Dani Alves", ["offensif", "technique", "flair"]],
    ["Ashley Cole", ["expert 1v1", "infranchissable"]],
    ["Marcelo", ["créatif", "spectaculaire", "imprévisible", "artiste"]],
    ["Javier Zanetti", ["professionnalisme", "polyvalent", "infatigable", "exemplaire"]],
    ["Joshua Kimmich", ["rigueur", "propreté", "efficacité"]],
    ["Bixente Lizarazu", ["Petit mais redoutable", "rigueur", "énergique"]],
    ["Gianluca Zambrotta", ["élégant", "polyvalent"]],
    ["Maicon", ["puissance", "précision", "solidité"]],
    ["David Alaba", ["intelligence de jeu", "régularité"]],
    ["Jordi Alba", ["rapide", "technique", "offensif"]],
    ["Trent Alexander-Arnold", ["qualité de passe", "vision de jeu", "jeu long"]],
    ["Kyle Walker", ["vitesse", "puissance", "rigueur défensive"]],
    ["Dani Carvajal", ["combattant infatigable", "équilibre offensif/défensif"]],
    ["Achraf Hakimi", ["explosif", "rapide", "intelligent", "polyvalent"]],
    ["Patrice Evra", ["énergique", "engagé", "solide", "moteur offensif"]],
    ["Alphonso Davies", ["vitesse", "audace offensive"]],
    ["Theo Hernandez", ["offensif", "puissant", "agressif", "finisseur"]]
  ],

  milieu: [
    ["Zinédine Zidane", ["puissance", "grâce", "technique"]],
    ["Luka Modric", ["intelligence", "qualité de passe"]],
    ["Xavi Hernandez", ["technique", "propre", "vision du jeu"]],
    ["Andres Iniesta", ["finesse", "vision du jeu"]],
    ["Lothar Matthaus", ["rigueur", "flair offensif", "complet"]],
    ["Michael Laudrup", ["créativité", "aisance technique"]],
    ["Steven Gerrard", ["puissance", "talent", "leadership", "charisme"]],
    ["Clarence Seedorf", ["polyvalence", "élégance"]],
    ["Kevin de Bruyne", ["chef d'orchestre", "vision", "régularité", "qualité de passe"]],
    ["Kaka", ["vitesse", "technique", "conduite de balle"]],
    ["Frank Lampard", ["intelligence", "timing", "complet", "finisseur"]],
    ["Paul Scholes", ["frappe puissante", "passe chirurgicale", "stratège", "chef d'orchestre"]],
    ["Rodri", ["pièce centrale", "placement", "puissance"]],
    ["Andrea Pirlo", ["meneur reculé", "vision", "toucher de balle", "cerveau", "élégance"]],
    ["Sergio Busquets", ["jeu simple", "équilibre", "intelligence tactique"]],
    ["Patrick Vieira", ["guerrier technique", "duels", "domination"]],
    ["N'Golo Kanté", ["humilité", "récupération", "infatigable", "exemplaire"]],
    ["Yaya Touré", ["force", "puissance", "finesse"]],
    ["Toni Kroos", ["régularité", "précision", "contrôle du tempo", "qualité de passe", "intelligence"]],
    ["Roy Keane", ["combativité", "volonté de gagner", "redoutable"]],
    ["Frank Rijkaard", ["élégant", "défendre et construire", "intelligence"]],
    ["Mesut Özil", ["qualité de passe", "créativité", "sens de l'occasion"]],
    ["Federico Valverde", ["puissance", "énergique", "endurance"]],
    ["Jude Bellingham", ["polyvalence", "puissance", "technique"]],
    ["Paul Pogba", ["irrégularité", "puissance", "créativité", "talentueux"]],
    ["Pedri", ["vista", "technique", "qualité de passe", "élégance"]],
    ["Vitinha", ["vista", "technique", "qualité de passe", "finition"]],
    ["Bruno Fernandes", ["qualité de passe", "coup franc", "contrôle du tempo", "intelligence"]]
  ],

  ailier: [
    ["Cristiano Ronaldo", ["Puissance", "Technique", "Finition", "Force"]],
    ["Lionel Messi", ["Dribble", "Vivacité", "Créativité", "Finition", "Précision"]],
    ["Ronaldinho", ["Magicien", "Dribbles", "Créativité"]],
    ["Luís Figo", ["Élégance", "Visionnaire", "Centre", "Dribble"]],
    ["David Beckham", ["Coups francs", "Centre", "Précision"]],
    ["Arjen Robben", ["Faux pied", "Frappe imparable", "Solide"]],
    ["Franck Ribéry", ["Percutant", "Imprévisible", "Dynamiteur de défense"]],
    ["Kylian Mbappé", ["Vitesse", "Technique", "Sens du but"]],
    ["Eden Hazard", ["Équilibre", "Vitesse", "Créativité", "Puissance"]],
    ["Ángel Di María", ["Polyvalent", "Technique", "Précision"]],
    ["Alexis Sánchez", ["Énergique", "Polyvalent", "Vivacité", "Sens du but"]],
    ["Sadio Mané", ["Puissance", "Explosif", "Imprévisible"]],
    ["Mohamed Salah", ["Finition", "Dribble"]],
    ["Ousmane Dembélé", ["Technique", "Deux pieds", "Vitesse", "Fragile"]],
    ["Adama Traoré", ["Force physique", "Vitesse"]],
    ["Neymar", ["artiste", "Dribble", "Vitesse", "Feinte"]],
    ["Vinícius Júnior", ["Provocateur", "Rapide", "Dribble"]],
    ["Lamine Yamal", ["Récréatif", "Dribble", "Passeur"]],
    ["Raphinha", ["Timing", "Finition", "Vitesse", "Abnégation"]],
    ["Michael Olise", ["Technique", "Frappe", "Vision de jeu", "Qualité de passe"]],
    ["Cole Palmer", ["Calme", "Créativité", "Décisif"]],
    ["Khvicha Kvaratskhelia", ["Flair", "Imprévisible", "Puissance", "Finition"]],
    ["Rafael Leão", ["Dribbleur explosif", "Accélération", "Vitesse"]],
    ["Désiré Doué", ["Dribble", "Fantaisie", "Technique"]]
  ],

  buteur: [
    ["Thierry Henry", ["vitesse", "créativité", "grâce"]],
    ["Luis Suárez", ["rage", "pressing du but", "finition"]],
    ["Robert Lewandowski", ["machine à but", "régularité", "efficacité"]],
    ["Wayne Rooney", ["puissance", "intelligence", "complet"]],
    ["Karim Benzema", ["Décisif", "Calme", "Complet"]],
    ["Andriy Shevchenko", ["rapide", "efficace", "imprévisible"]],
    ["Raúl", ["élégance", "intelligence", "sens du but"]],
    ["Zlatan Ibrahimović", ["charisme", "technique", "puissance", "acrobatie"]],
    ["Sergio Agüero", ["sens du but", "agilité", "décisif"]],
    ["Samuel Eto'o", ["vif", "puissant", "décisif", "sens du but"]],
    ["Ronaldo Nazário", ["puissance", "technique", "efficacité"]],
    ["Antoine Griezmann", ["intelligence", "généreux", "technique"]],
    ["Didier Drogba", ["puissance", "charisme", "clutch"]],
    ["Harry Kane", ["complet", "régulier", "décisif", "intelligence"]],
    ["Robin Van Persie", ["spectaculaire", "technique"]],
    ["Erling Haaland", ["puissance", "vitesse", "finition"]],
    ["David Villa", ["technique", "efficacité"]],
    ["Edinson Cavani", ["volume de jeu", "efficacité", "jeu de tête"]],
    ["Miroslav Klose", ["rigueur", "timing", "jeu de tête"]],
    ["Diego Costa", ["rugueux", "puissance", "caractère"]]
  ]
};
